{% set name = "heliclockter" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/heliclockter-{{ version }}.tar.gz
  sha256: 094a4e75d8f3c5cc1653ba82ceceee2efeaabfa693e9b2bc1dae3381d13c6ed1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - heliclockter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/channable/heliclockter
  summary: A robust way of dealing with datetimes in python by ensuring all datetimes are timezone aware at runtime.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
