schema_version: 1

context:
  name: heliclockter
  version: "2.1.0"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/heliclockter-${{ version }}.tar.gz
  sha256: 6eeaf88aaa1054c0227f351684b28b6cd7810f0708c31abac36e10c1352109b9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - heliclockter
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A robust way of dealing with datetimes in python by ensuring all datetimes are timezone aware at runtime.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/channable/heliclockter

extra:
  recipe-maintainers:
    - thewchan
