schema_version: 1

context:
  name: heliclockter
  version: 2.0.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/heliclockter-${{ version }}.tar.gz
  sha256: d7204ffdffb06a5abc1685a498ed44dd3e26ac0bd7e5b6829d307ea30498d57b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - heliclockter
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A robust way of dealing with datetimes in python by ensuring all datetimes are timezone aware at runtime.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/channable/heliclockter

extra:
  recipe-maintainers:
    - thewchan
